### ISSUE TITLE
Protocol 'Firebaseable' can only be used as a generic constraint because it has Self or associated type requirements

### ISSUE THREAD

**Issue by Germantv** [MihaelIsaev/FCM#11]
This error comes about when I declare the lines `extension Array where Element == Firebaseable { ... }`

It goes away when I change `return try Self.sendPush(title: title, message: message, token: token, on: req)` to `return try Firebaseable.sendPush(title: title, message: message, token: token, on: req)` located inside the first sendPush() function body, was there just a mistake in the ReadMe??

**Comment by MihaelIsaev** [comment]
Thank you for reporting, I've fixed that typo in example 🙂
