### ISSUE TITLE
Failing to refresh access token

### ISSUE THREAD

**Issue by hjuraev** [MihaelIsaev/FCM#19]
Abort 500: [FCM] Unable to refresh access token. Code: 400 Message: {
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."
})
[ ERROR ] ⚠️ Instants name: Abort 500: [FCM] Unable to refresh access token. Code: 400 Message: {
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."
})

**Comment by MihaelIsaev** [comment]
@hjuraev How to reproduce?

**Comment by MihaelIsaev** [comment]
My attempts to reproduce:
1) reduce JWT lifetime from 3600 seconds to 60 (just to test if refresh token logic even works) and send push notification every 1 minute
2) increase JWT lifetime from 60 to 120 seconds and send push notification every 3 minutes
3) set JWT lifetime to 3600 seconds(as it was) and send push every 3 minutes in next 2 hours

All three cases works, so I have no ideas how to reproduce your situation unfortunately
