### ISSUE TITLE
Fatal error when running migrations on terminal.

### ISSUE THREAD

**Issue by loopingGIT** [MihaelIsaev/FCM#24]
After I installed the package, now when trying to run my migrations I get this error:
```
Fatal error: FCM Unable to generate JWT: JWTKit error: signing algorithm error: signFailure: file 
/some_path/.build/checkouts/FCM/Sources/FCM/FCM.swift, line 72
```
If I comment out `app.fcm.configuration = .envServiceAccountKey` on the `configure` file, everything works.
This is just an issue when running migrations, the projects other than that works as expected.

**Comment by MihaelIsaev** [comment]
Could you make a test project where I can reproduce that issue?

**Comment by MihaelIsaev** [comment]
Or maybe it is happening because when you execute migrations it executes without environment variables? I just don't use `Fluent` so never tried to run their migrations unfortunately.

**Comment by loopingGIT** [comment]
Will try to recreate it in a new project. I also found this vapor/jwt-kit: https://github.com/vapor/jwt-kit/issues/26

To be honest don't know about the environment variable, will check.

**Comment by MihaelIsaev** [comment]
Do you use `.env` for environment variables file in that project? With it I believe it should work with both terminal and Xcode (don't forget to set custom working directory).

**Comment by loopingGIT** [comment]
Yes, I do use `.env` on this project, I have all my db connection info in there, so I guess is loaded just fine. I did set the working directory through xCode.

**Comment by MihaelIsaev** [comment]
Ok then it's weird 🙂 would be great if you could make some test project where this bug is easily reproducible

**Comment by jstorm31** [comment]
I'm facing basically the same problem. It might be related to https://github.com/vapor/jwt-kit/issues/26 and https://bugs.swift.org/browse/SR-12424.

**Comment by MihaelIsaev** [comment]
@jstorm31 this is interesting, thank you for links

**Comment by jstorm31** [comment]
I managed to isolate and reproduce the error. [Here's the repository](https://github.com/jstorm31/jwt-error-test). I get this error when running on CLI:
```
Fatal error: FCM Unable to generate JWT: JWTKit error: signing algorithm error: signFailure: file /Users/jstorm31/Dev/XCode/jwt-error-test/.build/checkouts/FCM/Sources/FCM/FCM.swift, line 72
[1]    94071 illegal hardware instruction  swift run
```

It might be really [the issues] I posted earlier. In that case, I guess there is no other option than wait for fixing it. What do you think @MihaelIsaev?

**Comment by LorDisturbia** [comment]
Is there any update on this? I've been seeing it on Xcode 12.5 and Swift 5.4. (with the same code that was working perfectly fine on a previous Xcode/Swift version)
