### ISSUE TITLE
ios Mutable Content

### ISSUE THREAD

**Issue by Mcrich23** [MihaelIsaev/FCM#41]
I am trying to enable mutable content in pushed and am using this data:
```
[
                    "badge": "0",
                    "sound": "default",
                    "mutable_content": "true",
                    "priority": "high",
                    // other stuff
                ]
```
why won't it run my code on the service extension?

**Comment by Mcrich23** [comment]
@MihaelIsaev ideas?

**Comment by Mcrich23** [comment]
even using apns specific stuff doesn't work

**Comment by Mcrich23** [comment]
but the firebase console does

**Comment by MihaelIsaev** [comment]
Hi @Mcrich23, sorry for the delayed response. Have you found a way to use `mutable_content` yet?

**Comment by Mcrich23** [comment]
Yes

**Comment by MihaelIsaev** [comment]
@Mcrich23 is any fix needed in the lib for that?

**Comment by Mcrich23** [comment]
@MihaelIsaev Sorry, I didn't see your response, but I did! I added `"mutable_content" : "true"` to the end of it
