### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by carmelogallo-foodics** [MihaelIsaev/FCM#46]
Hey @MihaelIsaev, 

is there any plans to support Async/Await?

**Comment by MihaelIsaev** [comment]
Hey @carmelogallo-foodics, yes it's in my plans since it is must have nowadays 🙂 as well as Hummingbird support

**Comment by carmelogallo** [comment]
@MihaelIsaev cool! Any ETA for it?

**Comment by MihaelIsaev** [comment]
@carmelogallo could you please try it from `async-await` branch?

**Comment by carmelogallo-foodics** [comment]
Sure man but I haven't started yet the integration. But looking at the code changes seems solid to me.

**Comment by MihaelIsaev** [comment]
Implemented in #48
