### ISSUE TITLE
FCMAndroidConfig internal initializer 

### ISSUE THREAD

**Issue by AlekseyPleshkov** [MihaelIsaev/FCM#51]
Hi! 
In release 3.0.0-beta `FCMAndroidConfig` initializer became internal. And now it's not possible to create this structure.

**Comment by AlekseyPleshkov** [comment]
[I have created PR here](https://github.com/MihaelIsaev/FCM/pull/52)

**Comment by MihaelIsaev** [comment]
Thank you, it is now available in `3.0.0-beta.2` 🤝
